jobs:
  checkstyle:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download Artifacts
      uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe
      with:
        commit: ${{ github.event.workflow_run.head_commit.id }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        name: checkstyle-results-${{ matrix.java }}
        workflow: ${{ github.event.workflow_run.workflow_id }}
        workflow_conclusion: completed
    - continue-on-error: true
      name: Publish Checkstyle Report
      uses: jwgmeligmeyling/checkstyle-github-action@50292990e18466f2c5d95d04ff5fab931254fa5f
      with:
        commit: ${{ github.event.workflow_run.head_commit.id }}
        name: Checkstyle Report JDK ${{ matrix.java }}
        path: '**/build/reports/checkstyle/*.xml'
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
  pmd:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download Artifacts
      uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe
      with:
        commit: ${{ github.event.workflow_run.head_commit.id }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        name: pmd-results-${{ matrix.java }}
        workflow: ${{ github.event.workflow_run.workflow_id }}
        workflow_conclusion: completed
    - continue-on-error: true
      name: Publish PMD Report
      uses: jwgmeligmeyling/pmd-github-action@322e346bd76a0757c4d54ff9209e245965aa066d
      with:
        commit: ${{ github.event.workflow_run.head_commit.id }}
        name: PMD Report JDK ${{ matrix.java }}
        path: '**/build/reports/pmd/*.xml'
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        java:
        - 8
        - 11
  spotbugs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download Artifacts
      uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe
      with:
        commit: ${{ github.event.workflow_run.head_commit.id }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        name: spotbugs-results-${{ matrix.java }}
        workflow: ${{ github.event.workflow_run.workflow_id }}
        workflow_conclusion: completed
    - continue-on-error: true
      name: Publish SpotBugs Report
      uses: jwgmeligmeyling/spotbugs-github-action@b8e2c3523acb34c87f14e18cbcd2d87db8c8584e
      with:
        commit: ${{ github.event.workflow_run.head_commit.id }}
        name: SpotBugs Report JDK ${{ matrix.java }}
        path: '**/build/reports/spotbugs/*.xml'
        token: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        java:
        - 8
        - 11
name: PR Quality Reports
on:
  repository_dispatch:
    types: trigger-ga___ci-prq-reports.yml
