jobs:
  quality:
    name: JDK ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Print JDK Version
      run: java -version
    - continue-on-error: true
      name: Make gradlew Executable
      run: chmod +x gradlew
    - continue-on-error: true
      name: Documentation Linter
      run: bash scripts/check-source-root.sh
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew --parallel clean quality
    - continue-on-error: true
      if: always()
      name: Upload CheckStyle Results
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle-results-${{ matrix.java }}
        path: '**/build/reports/checkstyle/*.xml'
    - continue-on-error: true
      if: always()
      name: Upload PMD Results
      uses: actions/upload-artifact@v4
      with:
        name: pmd-results-${{ matrix.java }}
        path: '**/build/reports/pmd/*.xml'
    - continue-on-error: true
      if: always()
      name: Upload SpotBugs Results
      uses: actions/upload-artifact@v4
      with:
        name: spotbugs-results-${{ matrix.java }}
        path: '**/build/reports/spotbugs/*.xml'
    strategy:
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
name: PR Quality
on:
  repository_dispatch:
    types: trigger-ga___ci-prq.yml
